{% set name = "gtkmm" %}
{% set version = "3.24.2" %}
{% set ver_maj_min = ".".join(version.split(".")[:2]) %}
{% set abi_version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/gtkmm/{{ ver_maj_min }}/gtkmm-{{ version }}.tar.xz
  sha256: 6d71091bcd1863133460d4188d04102810e9123de19706fb656b7bb915b4adc3

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - gtkmm-{{ abi_version }} >={{ version }}

outputs:
  - name: gtkmm-{{ abi_version }}
    script: build_gtkmm.sh
    build:
      run_exports:
        - gtkmm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - pkg-config
      host:
        - gtk3 >=3.24.0
        - glibmm >=2.54.0
        - cairomm >=1.12.0
        - pangomm >=2.38.2
        - sigcpp-2.0
        - atkmm >=2.24.2
        - cairo
        - glib
        - atk
        - gdk-pixbuf >=2.35.5
        - pango
        - glib
        - xorg-libice                # [linux]
        - xorg-libsm                # [linux]
        - xorg-libx11                # [linux]
        - xorg-libxcomposite                # [linux]
        - xorg-libxcursor                # [linux]
        - xorg-libxdamage                # [linux]
        - xorg-libxext                # [linux]
        - xorg-libxi                # [linux]
        - xorg-libxinerama                # [linux]
        - xorg-libxfixes                # [linux]
        - xorg-libxrandr                 # [linux]
        - xorg-libxrender                # [linux]
        - xorg-libxtst                # [linux]
        - libegl-devel                    # [linux]
        - libgl-devel                    # [linux]
        - xorg-xorgproto                     # [linux]
      run:
        - {{ pin_compatible("pango") }}
        - {{ pin_compatible("glibmm") }}
      run_constrained:
        - gtkmm {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libgtkmm-{{ abi_version }}${SHLIB_EXT}

  - name: gtkmm
    requirements:
      run:
        - gtkmm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/gtkmm-{{ abi_version }}.pc


about:
  home: https://www.gtkmm.org
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'C++ bindings for gtk'

extra:
  recipe-maintainers:
    - isuruf
